cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

instaswap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('', include('market.urls')),
]

market/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "market"
urlpatterns = [
    path('', views.store, name='store'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views

app_name='users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

cart/models.py
from django.db import models

# Create your models here.

market/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    email = models.EmailField()

    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=150)
    price = models.FloatField(null=True, blank=True)
    image = models.ImageField(upload_to='images', null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url = ''
        return url
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    complete = models.BooleanField(default=True)
    date_added = models.DateField(auto_now_add=True)
    transaction_id =  models.CharField(max_length=150)

    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    date_added = models.DateField(auto_now_add=True)
    quantity = models.IntegerField(default=0)

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True, blank=True)
    City = models.CharField(max_length=150)
    zipcode = models.CharField(max_length=150)
    address = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = 'ShippingAddresses'

    def __str__(self):
        return self.address
    

users/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from market.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')
@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

market/views.py
from django.shortcuts import render
from .models import *
from cart.forms import CartAddProductForm

# Create your views here.
def store(request):
    products = Product.objects.all()
    cart_product_form = CartAddProductForm()
    context = {'products': products, 'cart_product_form': cart_product_form}
    return render(request, 'market/store.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('market:store')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

cart/templates/cart/detail.html
{% extends 'market/base.html' %}
{% load static %}

{% block content %}
{% include 'market/navbar.html' %}
<div class="container">
    <h1 class="main-name">Your shopping cart</h1>
    <table class="cart container">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Unit Price</th>
                {% comment %} <th>Remove</th> {% endcomment %}
            </tr>
        </thead>
        <tbody class="cart-body">
            {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td class="table-data">
                        <a href="#">
                            <img src="{{product.imageURL}}">
                        </a>
                        </td>
                        <td>{{product.name}}</td>
                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                {% comment %} <input class='btn' type="submit" value="Update"> {% endcomment %}
                                {% csrf_token %}
                            </form>
                        </td>
                        
                        <td class="num">${{item.price}}</td>
                        <td class="num">${{item.total_price}}</td>
                        <td>
                            <form action="{% url 'cart:cart_remove' product.id%}" method="post">
                                <input class='btn btn-remove' type="submit" value="X">
                                {% csrf_token %}
                            </form>
                        </td>
                </tr>
                        
                    {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <span class="flex text-right">
        <a class="btn" href="{% url "market:store" %}" class="button light">Continue shopping</a>
        <a class="btn" href="#" class="button">Checkout</a>
    </span>

</div>
{% include 'market/footer.html' %}
{% endblock content %}

market/templates/market/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instaswapp</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

market/templates/market/footer.html
{% extends 'market/base.html' %}
{% load static %}

{% block content %}
<footer class="footer ">
    <div class="container grid grid-3">
        <div>
            <h1>Instaswap</h1>
            <p>Copyright &copy; 2020</p>
        </div>
        <nav>
            <ul>
                <li><a href="#">Plumbing</a></li>
                <li><a href="#">Electrical</a></li>
                <li><a href="#">Ceramics</a></li>
                <li><a href="#">Gypsum</a></li>
            </ul>
        </nav>
        <div class="social ">
            <ul>
           <li><a href="#">Contact us</a></li>
            <li><a href="#">About us</a></li>
            </ul>
        </div>
    </div>
</footer>

{% endblock content %}

market/templates/market/navbar.html
{% extends 'market/base.html' %}
{% load static %}

{% block content %}
<div class="navbar">
    <div class="container flex">
       <a href="{% url 'market:store'%}"> <h2 class="main-name">Instaswap</h2></a>
        <ul>
            <li><a href="#">Laptops</a></li>
            <li><a href="#">Phones</a></li>
            <li><a href="#">Electrical Appliances</a></li>
            <li><a href="#">Gaming</a></li>
        </ul>
        <div class='user'>
            {% if user.is_authenticated%}
              Hello, {{user.username}}
              <a href="{% url 'users:logout'%}">Log out</a>
              
            {%else%}
                <a href="{% url 'users:login'%}" class='login'>Login</a>
                <a href="{% url 'users:register'%}" class='login'>Register</a>

            {%endif%}
            <a href="{% url 'cart:cart_detail'%}" style="color:red;" class="cart">Cart</a>
    </div>
    
</div>

{% endblock content %}

market/templates/market/store.html
{% extends 'market/base.html' %}
{% load static %}
{% block content %}
{% include 'market/navbar.html' %}
<section class="showcase container">
    <div class="showcase-text">
        <h2 class="main-name">Explore electrical appliances</h2>
    </div>
    <div class="grid">
        {%for product in products%}
            <div class="card">
                <img src="{{product.imageURL}}" >
                <h4>{{product.name}}</h4>
                <h3>{{product.price}}<h3>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input class="btn" type="submit" value="Add to cart">
                </form>
            </div>
        {%endfor%}
    </div>
</section>
{% include 'market/footer.html' %}

{% endblock content %}